import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ArrowUpRight,ArrowLeft,ArrowRight,X,Instagram,Menu} from 'lucide-react';
import {asset,type Content} from './types';
import Editor from './Editor';
import FilmCarousel from './FilmCarousel';
import DetailPages, {ProjectSummary, ProjectDetailPage} from './DetailPages';
export default function App(){
 const [content,setContent]=useState<Content|null>(null),[error,setError]=useState(false),[category,setCategory]=useState('All work'),[selected,setSelected]=useState<string|null>(null),[menu,setMenu]=useState(false);
 const page=location.pathname.endsWith('/projects.html')?'projects':location.pathname.endsWith('/experience.html')?'experience':location.pathname.endsWith('/project.html')?'project':null;
 useEffect(()=>{if(page==='project') {const project=content?.projects?.find(p=>p.id===new URLSearchParams(location.search).get('id'));document.title=`${project?.title||'Project'} — zsho.ot`;}},[page,content]);
 const homeLink=(hash:string)=>page?`${asset('index.html')}${hash}`:hash;
 const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{fetch(asset('content.json')).then(r=>{if(!r.ok)throw Error();return r.json();}).then(setContent).catch(()=>setError(true));},[]);
 const photos=content?.photos.filter(p=>category==='All work'||p.category===category)||[];
 const index=photos.findIndex(p=>p.id===selected);const photo=photos[index];
 const move=(direction:number)=>setSelected(photos[(index+direction+photos.length)%photos.length].id);
 useEffect(()=>{if(selected){dialog.current?.showModal();document.body.style.overflow='hidden';}else {dialog.current?.close();document.body.style.overflow='';}return()=>{document.body.style.overflow='';};},[selected]);
 if(error)return <main className="loading"><h1>Couldn’t load the portfolio.</h1><button onClick={()=>location.reload()}>Try again</button></main>;
 if(!content)return <main className="loading">Opening the collection…</main>;
 if(location.pathname.endsWith('/edit') && import.meta.env.DEV)return <Editor initial={content}/>;
 return <>
 <header className={`header${page?' detail-header':''}`}><a className="wordmark header-wordmark" href={homeLink("#home")} aria-label="zsho.ot home"><img className="header-logo-icon" src={asset('brand/refine-icon.svg')} alt="" aria-hidden="true"/><div>{content.name}<span aria-hidden="true">•</span></div></a><nav aria-label="Main navigation" className={menu?'open':''}><a href={homeLink("#work")} onClick={()=>setMenu(false)}>Photography</a><a href={homeLink("#motion")} onClick={()=>setMenu(false)}>Motion</a><a href={homeLink("#about")} onClick={()=>setMenu(false)}>About me</a><a href={asset("projects.html")} aria-current={page==='projects'||page==='project'?'page':undefined} onClick={()=>setMenu(false)}>Projects</a><a href={asset("experience.html")} aria-current={page==='experience'?'page':undefined} onClick={()=>setMenu(false)}>Experience</a></nav><a className="header-social" href={content.instagram} target="_blank" rel="noreferrer">Instagram <ArrowUpRight size={15}/></a><button className="menu-button" aria-label="Toggle navigation" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 {page==='project'?<ProjectDetailPage content={content} projectId={new URLSearchParams(location.search).get('id')}/>:page?<DetailPages page={page} content={content}/>:<main>
 <section className="hero" id="home"><img className="hero-image" src={asset(content.hero)} alt={content.photos.find(p=>p.src===content.hero)?.alt||'Featured photograph by Yeah Jing Ze'} fetchPriority="high"/><div className="hero-shade"/><div className="hero-top"><span className="eyebrow"><i/> THROUGH MY LENS</span></div><div className="hero-content"><p className="eyebrow">PHOTOGRAPHY · FILM · FEELING</p><h1>Some moments<br/>deserve to <em>stay.</em></h1><p>{content.tagline}</p><a className="pill" href="#work">Explore my work <ArrowDown size={17}/></a></div><div className="hero-bottom"><span>{content.introduction}</span><a href="#work">SCROLL TO EXPLORE <ArrowDown size={14}/></a></div></section>
 <section className="work section" id="work"><div className="section-top"><span className="eyebrow muted">01 / PHOTOGRAPHY</span><span className="small muted">A collection, always growing.</span></div><div className="section-heading"><h2>Seen. Felt. <em>Captured.</em></h2><p>From the energy of a stage to the quiet of an ordinary day.<br/>A few moments through my eyes.</p></div><div className="filters" aria-label="Filter photographs">{['All work',...new Set(content.photos.map(p=>p.category))].map(c=><button key={c} className={category===c?'active':''} aria-pressed={category===c} onClick={()=>setCategory(c)}>{c}{c==='All work'&&<span>{content.photos.length.toString().padStart(2,'0')}</span>}</button>)}</div><div className="gallery">{photos.map((p,i)=><button key={p.id} className="photo-card" onClick={()=>setSelected(p.id)} aria-label={`Open ${p.title}`}><div className="photo-wrap"><img src={asset(p.src)} alt={p.alt} loading="lazy"/><span className="photo-open"><ArrowUpRight size={20}/></span></div><div className="photo-caption"><div><span className="photo-category">{p.category}</span><h3>{p.title}</h3></div><span className="photo-number">{(i+1).toString().padStart(2,'0')}</span></div></button>)}</div><div className="collection-end"><i/><span>Every frame, a little piece of my world.</span><i/></div></section>
 <section className="motion section" id="motion"><div className="section-top"><span className="eyebrow muted">02 / MOTION</span><span className="small muted">When a single frame isn’t enough.</span></div><div className="section-heading"><h2>Stories that <em>move.</em></h2><p>Finding rhythm in the everyday.<br/>A different way to keep a moment alive.</p></div><FilmCarousel films={content.films}/></section>
 <section className="about section" id="about"><div className="section-top"><span className="eyebrow muted">03 / BEHIND THE LENS</span></div><div className="about-grid"><div className="about-visual"><img src={asset('photos/me.JPG')} alt="Yeah Jing Ze" loading="lazy"/><span>THE WORLD, A LITTLE CLOSER.</span></div><div className="about-copy"><span className="eyebrow green">HELLO, I’M JING ZE.</span><h2>A curious eye.<br/>A story <em>to tell.</em></h2><p>{content.bio}</p><div className="experience"><span className="eyebrow muted">EXPERIENCE</span>{content.experience.map((e,i)=><div key={i} className="experience-row"><span className="experience-dot"/><div><h3>{e.company}<span>{e.role}</span></h3><p>{e.description}</p></div></div>)}<a className="text-link" href={asset("experience.html")}>View details <ArrowUpRight size={17}/><span className="sr-only"> about my experience</span></a></div><div className="kit"><span className="eyebrow muted">MY EVERYDAY KIT</span><div>{content.equipment.map(e=><span key={e}>{e}</span>)}</div></div></div></div></section>
 <ProjectSummary content={content}/>
 </main>}<footer><div className="footer-main"><a className="wordmark footer-brand" href={homeLink("#home")}><img src={asset('brand/refinelogo.png')} alt=""/>{content.name}<span aria-hidden="true">•</span></a><p>Moments pass. Stories stay.</p><a href={content.instagram} target="_blank" rel="noreferrer"><Instagram size={17}/> Follow the story <ArrowUpRight size={18}/></a></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Yeah Jing Ze</span><span>PHOTOGRAPHY & VISUAL STORYTELLING</span><a href="#home">Back to top ↑</a></div></footer>
 <dialog ref={dialog} className="lightbox" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}} onKeyDown={e=>{if(e.key==='ArrowRight')move(1);if(e.key==='ArrowLeft')move(-1);}}><button className="lightbox-close" aria-label="Close photograph" onClick={()=>setSelected(null)}><X/></button>{photo&&<><img src={asset(photo.src)} alt={photo.alt}/><div className="lightbox-bottom"><button aria-label="Previous photograph" onClick={()=>move(-1)}><ArrowLeft/></button><div><h3>{photo.title}</h3><span>{photo.category} · {index+1} / {photos.length}</span></div><button aria-label="Next photograph" onClick={()=>move(1)}><ArrowRight/></button></div></>}</dialog>
 </>;
}
