import {useEffect,useState} from 'react';
import {ArrowLeft,Save,Trash2,Plus,ArrowUp,ArrowDown} from 'lucide-react';
import {asset,type Content,type Photo,type Film} from './types';
export default function Editor({initial}:{initial:Content}){
 const [data,setData]=useState(initial),[token,setToken]=useState(''),[status,setStatus]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[tab,setTab]=useState('Photos');
 useEffect(()=>{fetch('/api/session').then(r=>r.json()).then(d=>setToken(d.token)).catch(()=>setStatus('Editor unavailable. Start the development server.'));},[]);
 useEffect(()=>{const warn=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 const change=(patch:Partial<Content>|((current:Content)=>Partial<Content>))=>{setData(current=>({...current,...(typeof patch==='function'?patch(current):patch)}));setDirty(true);setStatus('Unsaved changes');};
 const photo=(id:string,patch:Partial<Photo>)=>change(current=>({photos:current.photos.map(p=>p.id===id?{...p,...patch}:p)}));
 const film=(id:string,patch:Partial<Film>)=>change(current=>({films:current.films.map(f=>f.id===id?{...f,...patch}:f)}));
 async function upload(file:File){const r=await fetch(`/api/upload?name=${encodeURIComponent(file.name)}`,{method:'POST',headers:{'x-editor-token':token},body:file});const result=await r.json();if(!r.ok)throw Error(result.error);return result.src as string;}
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(e){setStatus(e instanceof Error?e.message:'Something went wrong.');}finally{setBusy(false);}}
 async function save(){await run(async()=>{const r=await fetch('/api/content',{method:'PUT',headers:{'Content-Type':'application/json','x-editor-token':token},body:JSON.stringify(data)});const result=await r.json();if(!r.ok)throw Error(result.error);setDirty(false);setStatus('Saved to your project. Refresh the portfolio to see your changes.');});}
 const field=(label:string,key:'name'|'tagline'|'introduction'|'bio'|'instagram',multiline=false)=><label>{label}{multiline?<textarea value={data[key]} rows={5} onChange={e=>change({[key]:e.target.value})}/>:<input value={data[key]} onChange={e=>change({[key]:e.target.value})}/>}</label>;
 return <main className="editor"><header className="editor-header"><a href="/" onClick={e=>{if(dirty&&!confirm('Leave without saving your changes?'))e.preventDefault();}}><ArrowLeft size={18}/> Portfolio</a><span className="wordmark">zsho.ot <small>/ studio</small></span><button className="pill" disabled={busy||!token} onClick={save}><Save size={16}/>{busy?'Working…':'Save changes'}</button></header><div className="editor-intro"><span className="eyebrow green">YOUR CREATIVE SPACE</span><h1>Make it <em>yours.</em></h1><p>Update your collection and your story. Saved changes stay in this project; publishing through Git makes them live.</p><p className="editor-status" role="status">{status||'Ready to edit.'}</p></div><div className="filters">{['Photos','Video','About & text'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Photos'&&<><div className="editor-toolbar"><span>{data.photos.length} photographs</span><label className="upload-button"><Plus size={16}/> Add photos<input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||!token} onChange={e=>{const files=Array.from(e.target.files||[]);e.target.value='';void run(async()=>{const added:Photo[]=[];for(const f of files){const src=await upload(f);added.push({id:crypto.randomUUID(),src,title:f.name.replace(/\.[^.]+$/,''),category:'Creative',alt:''});}change({photos:[...data.photos,...added]});});}}/></label></div><div className="editor-photos">{data.photos.map((p,i)=><article className="editor-card" key={p.id}><img src={asset(p.src)} alt={p.alt}/><div className="editor-fields"><label>Title<input value={p.title} onChange={e=>photo(p.id,{title:e.target.value})}/></label><label>Category<input list="categories" value={p.category} onChange={e=>photo(p.id,{category:e.target.value})}/></label><label>Image description<input value={p.alt} onChange={e=>photo(p.id,{alt:e.target.value})}/></label><div className="editor-actions"><button className={data.hero===p.src?'selected':''} onClick={()=>change({hero:p.src})}>{data.hero===p.src?'Cover photo':'Use as cover'}</button><button aria-label={`Move ${p.title} earlier`} disabled={i===0} onClick={()=>{const list=[...data.photos];[list[i-1],list[i]]=[list[i],list[i-1]];change({photos:list});}}><ArrowUp size={16}/></button><button aria-label={`Move ${p.title} later`} disabled={i===data.photos.length-1} onClick={()=>{const list=[...data.photos];[list[i+1],list[i]]=[list[i],list[i+1]];change({photos:list});}}><ArrowDown size={16}/></button><button aria-label={`Remove ${p.title}`} onClick={()=>{if(confirm('Remove this photo from the gallery?')){const remaining=data.photos.filter(x=>x.id!==p.id);change({photos:remaining,...(data.hero===p.src?{hero:remaining[0]?.src||''}:{})});}}}><Trash2 size={16}/></button></div><label className="upload-button">Replace photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)void run(async()=>{const src=await upload(f);change({photos:data.photos.map(x=>x.id===p.id?{...x,src}:x),...(data.hero===p.src?{hero:src}:{})});});}}/></label></div></article>)}</div><datalist id="categories">{['Portraits','Events','Candid','Creative','Street & travel'].map(c=><option key={c}>{c}</option>)}</datalist></>}
 {tab==='Video'&&<div className="editor-text"><button onClick={()=>change({films:[...data.films,{id:crypto.randomUUID(),title:'New film',description:'',url:'',poster:data.hero,type:'instagram'}]})}><Plus size={16}/> Add video</button>{data.films.map(f=><article className="editor-panel" key={f.id}><label>Title<input value={f.title} onChange={e=>film(f.id,{title:e.target.value})}/></label><label>Description<textarea value={f.description} onChange={e=>film(f.id,{description:e.target.value})}/></label><label>Source<select value={f.type} onChange={e=>film(f.id,{type:e.target.value as Film['type'],url:''})}><option value="instagram">Instagram link</option><option value="file">Video file</option></select></label>{f.type==='instagram'?<label>Instagram reel URL<input type="url" value={f.url} onChange={e=>film(f.id,{url:e.target.value})}/></label>:<label>Video file (MP4 / WebM, up to 64 MB)<input type="file" accept="video/mp4,video/webm" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>film(f.id,{url:await upload(file)}));}}/><small>{f.url||'No video uploaded yet.'}</small></label>}<div className="editor-cover"><img src={asset(f.poster)} alt={`Cover for ${f.title}`}/><div><label>Choose a gallery photo<select value={data.photos.some(p=>p.src===f.poster)?f.poster:''} disabled={busy} onChange={e=>film(f.id,{poster:e.target.value})}>{!data.photos.some(p=>p.src===f.poster)&&<option value="">Custom cover</option>}{data.photos.map(p=><option key={p.id} value={p.src}>{p.title}</option>)}</select></label><div className="cover-actions"><label className="upload-button">Upload cover<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy||!token} onChange={e=>{const file=e.target.files?.[0];e.target.value='';if(file)void run(async()=>film(f.id,{poster:await upload(file)}));}}/></label>{f.type==='instagram'&&<button disabled={busy||!token||!f.url.trim()} onClick={()=>void run(async()=>{setStatus('Getting the Instagram cover…');const response=await fetch('/api/instagram-cover',{method:'POST',headers:{'Content-Type':'application/json','x-editor-token':token},body:JSON.stringify({url:f.url})});const result=await response.json();if(!response.ok)throw Error(result.error);film(f.id,{poster:result.src});setStatus('Instagram cover imported. Save changes to keep it.');})}>{busy?'Working…':'Get Instagram cover'}</button>}</div><small>Upload a JPG, PNG or WebP from Finder. Instagram covers are imported when available and saved with your site.</small></div></div><button onClick={()=>{if(confirm('Remove this video?'))change({films:data.films.filter(x=>x.id!==f.id)});}}><Trash2 size={16}/> Remove video</button></article>)}</div>}
 {tab==='About & text'&&<div className="editor-text"><div className="editor-panel">{field('Website name','name')}{field('Home tagline','tagline')}{field('Introduction','introduction')}{field('About me','bio',true)}{field('Instagram profile URL','instagram')}<label>Equipment (one item per line)<textarea value={data.equipment.join('\n')} onChange={e=>change({equipment:e.target.value.split('\n')})}/></label></div><h2>Experience</h2>{data.experience.map((exp,i)=><div className="editor-panel" key={i}>{(['company','role','description'] as const).map(key=><label key={key}>{key}<input value={exp[key]} onChange={e=>change({experience:data.experience.map((x,j)=>j===i?{...x,[key]:e.target.value}:x)})}/></label>)}<button onClick={()=>change({experience:data.experience.filter((_,j)=>i!==j)})}>Remove experience</button></div>)}<button onClick={()=>change({experience:[...data.experience,{company:'',role:'',description:''}]})}><Plus size={16}/> Add experience</button></div>}
 </main>;
}
